//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public Province()
        {
            this.Users = new HashSet<User>();
            this.Venues = new HashSet<Venue>();
        }
    
        public int ProvinceId { get; set; }
        public string ProvinceName { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Venue> Venues { get; set; }
    }
}
