//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Notifications = new HashSet<Notification>();
            this.Requests = new HashSet<Request>();
            this.Tickets = new HashSet<Ticket>();
            this.Tickets1 = new HashSet<Ticket>();
            this.UserFollowEvents = new HashSet<UserFollowEvent>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public bool Active { get; set; }
        public bool IsVerified { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string IdentityCard { get; set; }
        public bool Sellable { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ProvinceId { get; set; }
    
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Province Province { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<Ticket> Tickets1 { get; set; }
        public virtual ICollection<UserFollowEvent> UserFollowEvents { get; set; }
    }
}
