//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropIt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Event
    {
        public Event()
        {
            this.Requests = new HashSet<Request>();
            this.Tickets = new HashSet<Ticket>();
            this.UserFollowEvents = new HashSet<UserFollowEvent>();
        }
    
        public int EventId { get; set; }
        public string EventName { get; set; }
        public string EventImage { get; set; }

        public string Artist { get; set; }

        [Display(Name = "Ngày tổ chức: ")]
        public System.DateTime HoldDate { get; set; }
        public string Description { get; set; }

        [Display(Name = "Trạng thái: ")]
        public int Status { get; set; }

        public int CategoryId { get; set; }
        public int VenueId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Venue Venue { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<UserFollowEvent> UserFollowEvents { get; set; }
    }
}
