//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.RespondRequests = new HashSet<RespondRequest>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public int TicketId { get; set; }
        public double SellPrice { get; set; }
        public double ReceiveMoney { get; set; }
        public string Seat { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public int UserId { get; set; }
        public int EventId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public byte[] ModifiedDate { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ICollection<RespondRequest> RespondRequests { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
        public virtual User User { get; set; }
    }
}
