//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketResponse
    {
        public int UserId { get; set; }
        public int EventId { get; set; }
        public int TicketId { get; set; }
        public int Status { get; set; }
        public string Description { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
