//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public int TransactionId { get; set; }
        public System.DateTime ShipDate { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public int Status { get; set; }
        public int TicketId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
