//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFollowUser
    {
        public int UserFollowUserId { get; set; }
        public int UserId { get; set; }
        public int UserFollowId { get; set; }
        public int FollowType { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
