//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Requests = new HashSet<Request>();
            this.Tickets = new HashSet<Ticket>();
            this.Transactions = new HashSet<Transaction>();
            this.UserFollowEvents = new HashSet<UserFollowEvent>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public int Status { get; set; }
        public int Role { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ProvinceId { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<UserFollowEvent> UserFollowEvents { get; set; }
    }
}
