//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public Venue()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int VenueId { get; set; }
        public string VenueName { get; set; }
        public string Address { get; set; }
        public int ProvinceId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual Province Province { get; set; }
    }
}
